version: "3.9"

services:
  mongodb:
    image: mongo
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

  postgres:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: school
      POSTGRES_USER: erickwendel
      POSTGRES_PASSWORD: mypassword

  redis-queue:
    image: redis
    ports:
      - "6379:6379"
    